version: '3.8'

services:
  db:
    image: postgres:15
    container_name: iwillread_db
    environment:
      POSTGRES_USER: baker
      POSTGRES_PASSWORD: UksBaJ5UH2pwL2bi9zfhVAiWoYkJkBom
      POSTGRES_DB: iwillread
    ports:
      - "5432:5432"

  iwillsew:
    build:
      context: .
    ports:
      - 9000:8000
    container_name: iwillread_application
    depends_on:
      - db
    command: ["/iwillread/docker/app.sh"]
    
