version: '3.8'

services:
  db:
    image: postgres:15
    container_name: iwillsew_db
    environment:
      POSTGRES_USER: baker
      POSTGRES_PASSWORD: MEg2U5wcih9AjCseeIpiJ9JNBByAFsYU
      POSTGRES_DB: iwillsew_database
    ports:
      - "5432:5432"

  iwillsew:
    build:
      context: .
    ports:
      - 9000:8000
    container_name: iwillsew_application
    depends_on:
      - db
    command: ["/iwillsew/docker/app.sh"]
    
