"""Add created_at column to product

Revision ID: 0094c1b8adf8
Revises: 9d2a3cd6dad9
Create Date: 2024-06-03 09:11:38.329992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0094c1b8adf8"
down_revision: Union[str, None] = "9d2a3cd6dad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "created_at")
    # ### end Alembic commands ###
