"""add order status table

Revision ID: 092b888e3126
Revises: bf7878c0e0b5
Create Date: 2024-06-19 22:46:04.730035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092b888e3126'
down_revision: Union[str, None] = 'bf7878c0e0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('orders', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'order_status', ['status_id'], ['id'])
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'Новый'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status_id')
    op.drop_table('order_status')
    # ### end Alembic commands ###
