"""Add is_superuser column to users

Revision ID: 16d9f22f3839
Revises: 7c1b23c0007c
Create Date: 2024-05-31 11:15:40.307910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16d9f22f3839"
down_revision: Union[str, None] = "7c1b23c0007c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    # # ### end Alembic commands ###
    # op.execute("UPDATE users SET is_superuser = FALSE WHERE is_superuser IS NULL")

    # # 3. Измените столбец, добавив ограничение NOT NULL
    # op.alter_column("users", "is_superuser", nullable=False)
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
