"""update product model(add count_pages, author etc.)

Revision ID: 16f79757b987
Revises: 17ee7754008d
Create Date: 2024-06-23 17:06:45.462417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f79757b987'
down_revision: Union[str, None] = '17ee7754008d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('author', sa.String(), nullable=True))
    op.add_column('products', sa.Column('year', sa.String(), nullable=True))
    op.add_column('products', sa.Column('years_old', sa.String(), nullable=True))
    op.add_column('products', sa.Column('count_pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'count_pages')
    op.drop_column('products', 'years_old')
    op.drop_column('products', 'year')
    op.drop_column('products', 'author')
    # ### end Alembic commands ###
