"""update product model(add author relationship)

Revision ID: 323b03134008
Revises: 16f79757b987
Create Date: 2024-06-23 17:30:26.940445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323b03134008'
down_revision: Union[str, None] = '16f79757b987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'authors', ['author_id'], ['id'])
    op.drop_column('products', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'author_id')
    op.drop_table('authors')
    # ### end Alembic commands ###
