"""delete enum order-statuses

Revision ID: 37fce157c89e
Revises: d675bc1062f4
Create Date: 2024-06-19 21:24:42.511558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37fce157c89e'
down_revision: Union[str, None] = 'd675bc1062f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('Новый', 'В обработке', 'Отправлен', 'Доставлен', 'Отменен', name='orderstatusenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('Новый', 'В обработке', 'Отправлен', 'Доставлен', 'Отменен', name='orderstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
