"""Add orderstatus and decline description to the tables v2

Revision ID: 4f8ebfabc61d
Revises: e9647576e933
Create Date: 2024-06-18 20:14:10.518522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8ebfabc61d'
down_revision: Union[str, None] = 'e9647576e933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
