"""Add cart table

Revision ID: 8f5f1fb39cef
Revises: b28f3b5fb374
Create Date: 2024-06-03 23:19:37.524475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f5f1fb39cef"
down_revision: Union[str, None] = "b28f3b5fb374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
