"""add default to order status

Revision ID: bf7878c0e0b5
Revises: 37fce157c89e
Create Date: 2024-06-19 21:28:07.871446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf7878c0e0b5"
down_revision: Union[str, None] = "37fce157c89e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.String(),
        nullable=False,
        server_default="Новый",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
