"""update product model(add author image and description)

Revision ID: d15cbafffe60
Revises: 323b03134008
Create Date: 2024-06-23 17:57:02.061222

"""

from typing import Sequence, Union

from alembic import op
import fastapi_storages.integrations.sqlalchemy

from products.models import storage
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d15cbafffe60"
down_revision: Union[str, None] = "323b03134008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authors",
        sa.Column(
            "image",
            fastapi_storages.integrations.sqlalchemy.FileType(storage=storage),
            nullable=True,
        ),
    )
    op.add_column("authors", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("authors", "description")
    op.drop_column("authors", "image")
    # ### end Alembic commands ###
