"""Add orders and order_items tables

Revision ID: dd4cef4e7674
Revises: 28ed44da3485
Create Date: 2024-06-06 10:15:46.331313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd4cef4e7674"
down_revision: Union[str, None] = "28ed44da3485"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     'cart_items',
    #     sa.Column('id', sa.Integer, primary_key=True),
    #     sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id')),
    #     sa.Column('product_id', sa.Integer, sa.ForeignKey('products.id')),
    #     sa.Column('quantity', sa.Integer)
    # )
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
