"""Add orderstatus and decline description to the tables

Revision ID: e9647576e933
Revises: fd6bf23aa822
Create Date: 2024-06-18 20:10:25.044470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9647576e933"
down_revision: Union[str, None] = "fd6bf23aa822"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "order_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_statuses_id"), "order_statuses", ["id"], unique=False
    )
    op.add_column("orders", sa.Column("decline_desc", sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "decline_desc")
    op.drop_index(op.f("ix_order_statuses_id"), table_name="order_statuses")
    op.drop_table("order_statuses")
    # ### end Alembic commands ###
